// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BookBorrowing.DATA.Models
{
    public partial class Book
    {
        public Book()
        {
            Borrowing = new HashSet<Borrowing>();
        }

        [Key]
        [Column("idBook")]
        public int IdBook { get; set; }

        [Required]
        [Column("bookName")]
        [StringLength(100)]
        [Display(Name = "Nome")]
        public string BookName { get; set; }

        [Required]
        [Column("authorName")]
        [StringLength(150)]
        [Display(Name = "Autor")]
        public string AuthorName { get; set; }

        [Column("publisherName")]
        [StringLength(150)]
        [Display(Name = "Editora")]
        public string PublisherName { get; set; }

        [Column("publishDate", TypeName = "date")]
        [Display(Name = "Data")]
        public DateTime PublishDate { get; set; }

        [Column("bookEdition")]
        [StringLength(50)]
        [Display(Name = "Edição")]
        public string BookEdition { get; set; }

        [Column("bookImg")]
        [Unicode(false)]
        [Display(Name = "Imagem")]
        public string BookImg { get; set; }

        [InverseProperty("IdBookNavigation")]
        public virtual ICollection<Borrowing> Borrowing { get; set; }
    }
}