// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BookBorrowing.DATA.Models
{
    public partial class Borrowing
    {
        [Key]
        [Column("idBorrowing")]
        public int IdBorrowing { get; set; }
        [Column("idBook")]
        public int IdBook { get; set; }
        [Column("idClient")]
        public int IdClient { get; set; }
        [Column("borrowingDate", TypeName = "datetime")]
        public DateTime BorrowingDate { get; set; }
        [Column("devolutionDate", TypeName = "datetime")]
        public DateTime DevolutionDate { get; set; }
        [Required]
        [Column("borrowingAdress")]
        [StringLength(100)]
        public string BorrowingAdress { get; set; }

        [ForeignKey("IdBook")]
        [InverseProperty("Borrowing")]
        public virtual Book IdBookNavigation { get; set; }
        [ForeignKey("IdClient")]
        [InverseProperty("Borrowing")]
        public virtual Client IdClientNavigation { get; set; }
    }
}