// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BookBorrowing.DATA.Models
{
    [Keyless]
    public partial class Library
    {
        [Column("idLibrary")]
        public int IdLibrary { get; set; }
        [Required]
        [Column("libraryName")]
        [StringLength(255)]
        public string LibraryName { get; set; }
        [Required]
        [Column("libraryEmail")]
        [StringLength(100)]
        public string LibraryEmail { get; set; }
        [Required]
        [Column("libraryPassword")]
        [StringLength(15)]
        public string LibraryPassword { get; set; }
    }
}